//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoubCompilator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoubCompilerEntities : DbContext
    {
        public CoubCompilerEntities()
            : base("name=CoubCompilerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoadedCoubs> LoadedCoubs { get; set; }
        public virtual DbSet<UploadedCompilations> UploadedCompilations { get; set; }
        public virtual DbSet<UsedCoubs> UsedCoubs { get; set; }
    }
}
