//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoubCompilator
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadedCoubs
    {
        public int ID { get; set; }
        public string Permalink { get; set; }
        public string Title { get; set; }
        public double DurationVideo { get; set; }
        public string Path { get; set; }
        public Nullable<int> LikesCount { get; set; }
        public Nullable<double> DurationSound { get; set; }
        public string PathVideo { get; set; }
        public string PathSound { get; set; }
        public string PathBlured { get; set; }
        public string PathCoub { get; set; }
        public Nullable<int> ViewsCount { get; set; }
        public Nullable<int> RemixesCount { get; set; }
        public Nullable<int> RecoubsCount { get; set; }
        public Nullable<int> DislikesCount { get; set; }
        public string UrlVideo { get; set; }
        public string UrlAudio { get; set; }
        public Nullable<System.DateTime> DateLoaded { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
