//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoubCompilator
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedCoubs
    {
        public int ID { get; set; }
        public string Permalink { get; set; }
        public Nullable<int> UploadedCompilations_ID { get; set; }
    }
}
